### ISSUE TITLE
借助 Code Review 工具检测到的一些问题

### ISSUE THREAD

**Issue by idranme** [koishijs/boilerplate#15]
见 https://www.codefactor.io/repository/github/koishijs/boilerplate/issues

**Comment by ilharp** [comment]
https://mastodon.social/@danluu/110335983520055904

提出你自己的见解。我们使用 `cat` 是因为 `cat` 能被大多数人更快地理解代码的作用，使用 `--from=0` 是因为 stage 只有两个，只为一个 stage 加 alias 毫无意义。前两个重构建议我认为均会降低代码的可读性，剩下的我懒得看了。不要拿无意义的重构浪费大家的时间。

**Comment by idranme** [comment]
> https://mastodon.social/@danluu/110335983520055904
> 
> 提出你自己的见解。我们使用 `cat` 是因为 `cat` 能被大多数人更快地理解代码的作用，使用 `--from=0` 是因为 stage 只有两个，只为一个 stage 加 alias 毫无意义。前两个重构建议我认为均会降低代码的可读性，剩下的我懒得看了。不要拿无意义的重构浪费大家的时间。
> 

嗷
