### ISSUE TITLE
bug:2.1.1版本的config无法保存插件分组过滤器

### ISSUE THREAD

**Issue by imAkisa** [koishijs/boilerplate#18]
2.1.1版本的config无法保存插件分组过滤器，2.0版本的可以
具体体现是填完了分组的过滤器后，右上角的√他不亮，无法保存，点一下别的分组再点回去，刚填的过滤器就被清空了

**Comment by ilharp** [comment]
Duplicate of https://github.com/koishijs/webui/issues/188

请等待上述 issue 修复
